name = "embedded_flexbox"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
maintainers-logins = ["github-username"]

executables = ["embedded_flexbox"]

[[depends-on]]
stm32f746disco = "0.1.0-dev"
stm32_gui = "~0.1.0-dev"
[[pins]]
gnat_arm_elf = { version='12.2.1' }