name = "embedded_flexbox"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
maintainers-logins = ["github-username"]

executables = ["embedded_flexbox"]

[build-switches]
"*".style_checks = "No"

[[pins]]
gnat_arm_elf = { version='12.2.1' }
[[depends-on]]
stm32_gui = "~0.1.0-dev"
stm32f746disco = "~0.1.0-dev"